#!/bin/sh
# Autori:
# @Pinperepette	
# @Daniele_KK
#########################################################################
#  This program is free software; you can redistribute it and/or modify #
#  it under the terms of the GNU General Public License as published by #
#  the Free Software Foundation; either version 2 of the License, or    #
#  (at your option) any later version.                                  #
#                                                                       #
#  This program is distributed in the hope that it will be useful,      #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of       #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #
#  GNU General Public License for more details.                         #
#                                                                       #
#  You should have received a copy of the GNU General Public License    #
#  along with this program; if not, write to the Free Software          #
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,           #
#  MA 02110-1301, USA.                                                  #
############################# DISCALIMER ################################
#  Usage of this software for probing/attacking targets without prior   #
#  mutual consent, is illegal. It's the end user's responsability to    #
#  obey alla applicable local laws. Developers assume no liability and  #
#  are not responible for any missue or damage caused by thi program    #
#########################################################################
prog="Penmode Backbox Edition"

Encoding=UTF-8

[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

 echo $ip
MAIN_DIALOG='
<window title="Penmode Informations"resizable="false" image-name="/opt/penmode_BB/images/icons/inf.png" >
        <vbox>
		<pixmap>
					<input file>/opt/penmode_BB/images/logo_bb.gif</input>
				</pixmap>
		<pixmap>
					<input file>/opt/penmode_BB/images/info.png</input>
				</pixmap>
	 </vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
