#!/bin/sh
# Autori:
# @Pinperepette	
# @Daniele_KK
#########################################################################
#  This program is free software; you can redistribute it and/or modify #
#  it under the terms of the GNU General Public License as published by #
#  the Free Software Foundation; either version 2 of the License, or    #
#  (at your option) any later version.                                  #
#                                                                       #
#  This program is distributed in the hope that it will be useful,      #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of       #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #
#  GNU General Public License for more details.                         #
#                                                                       #
#  You should have received a copy of the GNU General Public License    #
#  along with this program; if not, write to the Free Software          #
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,           #
#  MA 02110-1301, USA.                                                  #
############################# DISCALIMER ################################
#  Usage of this software for probing/attacking targets without prior   #
#  mutual consent, is illegal. It's the end user's responsability to    #
#  obey alla applicable local laws. Developers assume no liability and  #
#  are not responible for any missue or damage caused by thi program    #
#########################################################################
prog="Penmode Backbox Edition"

Encoding=UTF-8
if [ -z "$TARGET" ]; then
	notify-send -t 8000 -i /opt/penmode_BB/images/icons/alert.png 'Alert' 'Enter the Target'
else
[ -z $GTKDIALOG ] && GTKDIALOG=gtkdialog

 echo $ip
MAIN_DIALOG='
<window title="Penmode BackBox Edition Serch URL"resizable="false" image-name="/opt/penmode_BB/images/icons/cercaurl.png" >
        <vbox>
		<pixmap>
					<input file>/opt/penmode_BB/images/searchurl.gif</input>
				</pixmap>
			<frame TARGET>
        <entry>
			<default>'$TARGET'</default>
			<variable>TARGET</variable>
		</entry>
		</frame>
		<frame>
		 <hbox>
		 
			   <combobox>
               <variable>livel</variable>
			   <item>Ghost Scan</item>
               <item>Default Scan</item>
               <item>Uber Scan</item>
               </combobox> 
               <text>
			   <label>  SLEEP :</label>
			   </text>
               <entry>
			   <default>2</default>
			   <variable>sleep</variable>
		       </entry> 
		       <button>
		<input file>/opt/penmode_BB/images/icons/cercaurl.png</input>
		<width>30</width>
          <action>/opt/penmode_BB/modules/urlanalisi | zenity --text-info  --width=700 --height=500 --title "link scanner by Penmode2" &</action>
        </button>
            
         </hbox> 
         </frame>
	 </vbox>
</window>
'
export MAIN_DIALOG

case $1 in
	-d | --dump) echo "$MAIN_DIALOG" ;;
	*) $GTKDIALOG --program=MAIN_DIALOG ;;
esac
fi
